-- MedSafe AI Supabase Database Schema Setup
-- Copy and run this script in your Supabase SQL Editor:
-- https://supabase.com/dashboard/project/_/sql/new

-- 1. Users Table
CREATE TABLE IF NOT EXISTS public.users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email TEXT UNIQUE NOT NULL,
    username TEXT NOT NULL,
    password_hash TEXT,
    provider TEXT NOT NULL DEFAULT 'local',
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    patient_id TEXT UNIQUE
);

-- 2. Doctor Patients Relationship Table
CREATE TABLE IF NOT EXISTS public.doctor_patients (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    doctor_email TEXT NOT NULL,
    patient_email TEXT NOT NULL,
    added_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    UNIQUE(doctor_email, patient_email)
);

-- 3. Lab Reports Table
CREATE TABLE IF NOT EXISTS public.lab_reports (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_email TEXT NOT NULL,
    filename TEXT NOT NULL,
    report_label TEXT NOT NULL,
    file_content_text TEXT DEFAULT '',
    ai_analysis TEXT DEFAULT '',
    uploaded_at TEXT DEFAULT ''
);

-- Enable Row Level Security (RLS) policies for anon access
ALTER TABLE public.users ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.doctor_patients ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.lab_reports ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Allow anon read/write users" ON public.users FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Allow anon read/write doctor_patients" ON public.doctor_patients FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Allow anon read/write lab_reports" ON public.lab_reports FOR ALL USING (true) WITH CHECK (true);
